### ISSUE TITLE
Update Record in Fastapi

### ISSUE THREAD

**Issue by lsabi** [tortoise/tortoise-orm#606] opened 2021-01-09 22:47 UTC
**Describe the bug**
After creating via `POST` a new record in the database, one may need to update certain fields of it. When exposed via `Fastapi`, the `PUT` request has to contain the field that we want to update plus all the mandatory fields (i.e. non nullable). 

**To Reproduce**
To reproduce, I've used the example in the docs [https://tortoise-orm.readthedocs.io/en/latest/examples/fastapi.html#example-fastapi](https://tortoise-orm.readthedocs.io/en/latest/examples/fastapi.html#example-fastapi)

When run normally (instead of running it via `pytest`), navigate to the location in the browser (usually `localhost:8000/docs`), create a new user via the `swagger` interface, then update that user with `PUT`, updating any field but the one required (that is, any field but `username`). It will return `error 422` claiming that `username` is a mandatory field.

**Expected behavior**
It is to be expected a response with status code `200`, assuming a correct value has been submitted and no other exception occurred.

**Additional context**
I haven't tested it via other frameworks, so I've no clue if it's an error present for other frameworks as well.

**Comment by Abdeldjalil-H** [comment] 2024-11-14 21:52
I think this issue has nothing to do with `tortoise-orm`. It is `fastapi` or `pydantic` question. @henadzit

**Comment by henadzit** [comment] 2024-11-15 10:21
@Abdeldjalil-H I agree that it looks like that. Thanks for checking!

@lsabi can you please provide actual code to reproduce the issue? It's hard to judge what happened without the code. I'm closing the issue for now but feel free to reopen.

**Closed by henadzit** 2024-11-15 10:21 UTC
