### ISSUE TITLE
`Filter` not working correctly.

### ISSUE THREAD

**Issue by MohammadrezaAmani** [tortoise/tortoise-orm#1818] opened 2024-12-19 11:29 UTC
**Describe the bug**  
The `exclude` query in Tortoise ORM, when filtering providers based on whether a user has a token, does not return the expected results. Specifically, when querying providers that a specific user does not have a token for, it returns an empty list even when some providers should be excluded.

**To Reproduce**  
1. Define models (`Provider`, `Token`, etc.) with correct relationships (ForeignKey between `Token` and `Provider`).
2. Use the following code to filter providers for a user who does not have tokens:

```python
async def get_providers_without_tokens(user_id: int):
    providers_without_tokens = await Provider.exclude(tokens__user_id=user_id).all()
    return providers_without_tokens
```

3. Call the function with a `user_id` (e.g., `1`):

```python
await get_providers_without_tokens(1)
```

**Expected behavior**  
The expected behavior is that the query should return a list of providers where the user does not have an associated token. However, the actual behavior is that an empty list is returned, even when some providers should be included.

expected query:

```sql
SELECT * FROM provider
WHERE provider.id NOT IN (
    SELECT provider_id FROM token WHERE user_id = 1
);
```

**Additional context**  
The issue might be related to the way the `exclude` filter is working with the `ForeignKey` relationship between `Provider` and `Token`. There could be issues with how `Tortoise ORM` translates the query, or the model relationships might not be properly defined.

**models**

```python
from tortoise import fields

from src.base import BaseModel

class Provider(BaseModel):
    name = fields.CharField(max_length=256, null=True)
    url = fields.CharField(max_length=256, null=True)
    short_description = fields.CharField(max_length=256, null=True)
    description = fields.TextField(default="")


class Token(BaseModel):
    user = fields.ForeignKeyField("models.User", "tokens")
    token = fields.CharField(max_length=256, null=True)
    provider = fields.ForeignKeyField("models.Provider", "tokens")
```

**Comment by Abdeldjalil-H** [comment] 2024-12-19 15:56
Hi @MohammadrezaAmani.
Can you please add data to the tables and what output you expect. It is hard to tell without having any data.
Also can you combine all the code in one file that can be run immediately?

**Comment by waketzheng** [comment] 2024-12-20 10:13
I run the code in a single file:
```py
from __future__ import annotations

from tortoise import Model, fields, run_async
from tortoise.contrib.test import init_memory_sqlite


class User(Model):
    id = fields.IntField(pk=True)
    name = fields.CharField(max_length=256, null=True)


class Provider(Model):
    name = fields.CharField(max_length=256, null=True)


class Token(Model):
    user: fields.ForeignKeyRelation[User] = fields.ForeignKeyField("models.User", "tokens")
    token = fields.CharField(max_length=256, null=True)
    provider: fields.ForeignKeyRelation[Provider] = fields.ForeignKeyField(
        "models.Provider", related_name="tokens"
    )


async def get_providers_without_tokens(user_id: int) -> list[Provider]:
    providers_without_tokens = await Provider.exclude(tokens__user_id=user_id).all()
    return providers_without_tokens


@init_memory_sqlite
async def run() -> None:
    user = await User.create(name="Tim")
    provider = await Provider.create(name="Paul")
    token = await Token(token="xxx", user=user, provider=provider)
    user_id = user.id
    qs = Provider.exclude(tokens__user_id=user_id).all()
    print(qs.sql())
    print(await qs)
    provider_objs = await get_providers_without_tokens(user_id)
    print(token.provider not in provider_objs)


if __name__ == "__main__":
    run_async(run())
```
Got:
```
SELECT "provider"."name","provider"."id" FROM "provider" LEFT OUTER JOIN "token" ON "provider"."id"="token"."provider_id" WHERE NOT "token"."user_id"=?
[]
True
```

Seems that it's not a bug.

**Comment by henadzit** [comment] 2024-12-20 19:46
@MohammadrezaAmani to have the query you mentioned, you can use the following syntax: 

`await Provider.filter(id__not_in=Subquery(Token.filter(user_id=1).values("provider_id")))`

But I agree with others, filtering is working correctly. Closing the issue, please feel free to reopen.

**Closed as completed** 2024-12-20 19:46 UTC
