### ISSUE TITLE
sqlite syntax error for ManyToManyField.all().delete()

### ISSUE THREAD

**Issue by PromyLOPh** [tortoise/tortoise-orm#331] opened 2020-03-24 08:51 UTC
**Describe the bug**
Constructing the query for ManyToManyField.all().delete() fails with sqlite backend. The error message is `sqlite3.OperationalError: near "LEFT": syntax error` and the constructed query is `DELETE FROM "b" LEFT OUTER JOIN "a_b" ON "b"."id"="a_b"."b_id" WHERE "a_b"."a_id"=1`.

**To Reproduce**
Minimal testcase:
```python
import logging
from tortoise.models import Model
from tortoise import fields
from tortoise import Tortoise, fields, run_async
from tortoise.exceptions import DoesNotExist, IntegrityError
from tortoise.transactions import in_transaction

class A (Model):
	x = fields.IntField ()
	y = fields.ManyToManyField ('models.B')

class B (Model):
	z = fields.IntField ()

async def run():
	await Tortoise.init(db_url="sqlite://:memory:", modules={"models": ["__main__"]})
	await Tortoise.generate_schemas()

	# add data
	a = A (x=1)
	await a.save ()

	b = B (z=2)
	await b.save ()

	await a.y.add (b)

	# verify it’s there
	a = await A.get (x=1)
	assert (await a.y.all ()) == [b]

	# trigger the bug
	await a.y.all ().delete ()

	# verify
	a = await A.get (x=1)
	assert (await a.y.all ()) == []

if __name__ == "__main__":
	logging.basicConfig(level=logging.DEBUG)
	run_async(run())
```

**Expected behavior**
All elements in a.y should be removed from the database and the relation.

**Additional context**
```
tortoise-orm==0.16.2
aiosqlite==0.11.0
```

**Comment by grigi** [comment] 2020-03-24 18:47
Thanks for the bugreport. 
I just want some clarity as to what you want to happen here?
Do you want to delete:
a. The relation between A & B
OR
b. all B entries in the relation? (and relations in a_b for referential integrity)

**Comment by PromyLOPh** [comment] 2020-03-24 18:58
The latter. I would expect all() to select all B’s that are related to a and then delete them. If the first one was intended I could’ve used `a.y.remove (*a.y)`, right?

**Comment by grigi** [comment] 2020-03-24 19:36
`a.y.clear()` would remove all relations for you.

Thanks for the clarification, This is a duplicate of #283 → https://github.com/tortoise/tortoise-orm/issues/283#issuecomment-581628897 describes what needs to be done. Unfortunately the SQL we generate for joins don't make sense for DELETE operations at all.

**Closed** 2020-03-24 19:37 UTC
Labels: duplicate
