### ISSUE TITLE
Use F expression in Annotation

### ISSUE THREAD

**Issue by Arteemoon** [tortoise/tortoise-orm#995] opened 2021-12-01 21:28 UTC
```python
await User.annotate(
        tournament_count=Count('tournaments'),
        cc = F('tournament_count') / 2
    )
```

in console always get  -> "tortoise.exceptions.OperationalError: column "tournament_count" does not exist"
version 0.17.8

**Comment by divadsn** [comment] 2023-05-22 14:18
Duplicate of #683

**Closed** 2024-11-10 09:40 UTC
