### ISSUE TITLE
Tortoise init logs DB password in plain text. 

### ISSUE THREAD

**Issue by dropoftruth** [tortoise/tortoise-orm#595] opened 2020-12-23 02:09 UTC
**Describe the bug**
Tortoise init logs DB password in plain text. Logging is done on str(connections_config). 
```
logger.info(
            "Tortoise-ORM startup\n    connections: %s\n    apps: %s",
            str(connections_config),
            str(apps_config),)
```
**To Reproduce**
I was able to reproduce this by enabling logging to INFO level in my Sanic app 

`logging.basicConfig(level=logging.INFO)`

**Expected behavior**
Password should never be logged in plain text. An alternative to simple `str` while logging is needed

**Additional context**

**Comment by nkonin** [comment] 2021-01-11 06:12
Looks like duplicate of #449. Logging level for credentials was changed to `DEBUG` level in 0.16.19 release. See MR #560.

**Comment by WisdomPill** [comment] 2021-01-23 13:39
@nkonin can we close this then?

**Closed** 2021-01-23 13:46 UTC
