### ISSUE TITLE
ORDER BY related model fields exception

### ISSUE THREAD

**Issue by aalexfvk** [tortoise/tortoise-orm#461] opened 2020-07-20 15:51 UTC
Arguably, ordering by related model field does not work.
I use version 0.16.13 and Postgres 12.3
And try to run filtering [example](https://tortoise-orm.readthedocs.io/en/latest/examples/basic.html?highlight=order_by#filtering)
This statement raise an exception:
````
    print(
        await Event.filter(Q(id__in=[event_first.id, event_second.id]) | Q(name="3"))
        .filter(participants__not=team_second.id)
        .order_by("tournament__id")
        .distinct()
    )
````

````
Traceback (most recent call last):
  File "/home/admin/projects/python/workspace/.venv/lib/python3.8/site-packages/tortoise/backends/asyncpg/client.py", line 36, in translate_exceptions_
    return await func(self, *args)
  File "/home/admin/projects/python/workspace/.venv/lib/python3.8/site-packages/tortoise/backends/asyncpg/client.py", line 172, in execute_query
    rows = await connection.fetch(*params)
  File "/home/admin/projects/python/workspace/.venv/lib/python3.8/site-packages/asyncpg/connection.py", line 420, in fetch
    return await self._execute(query, args, 0, timeout)
  File "/home/admin/projects/python/workspace/.venv/lib/python3.8/site-packages/asyncpg/connection.py", line 1402, in _execute
    result, _ = await self.__execute(
  File "/home/admin/projects/python/workspace/.venv/lib/python3.8/site-packages/asyncpg/connection.py", line 1411, in __execute
    return await self._do_execute(query, executor, timeout)
  File "/home/admin/projects/python/workspace/.venv/lib/python3.8/site-packages/asyncpg/connection.py", line 1423, in _do_execute
    stmt = await self._get_statement(query, None)
  File "/home/admin/projects/python/workspace/.venv/lib/python3.8/site-packages/asyncpg/connection.py", line 328, in _get_statement
    statement = await self._protocol.prepare(stmt_name, query, timeout)
  File "asyncpg/protocol/protocol.pyx", line 163, in prepare
asyncpg.exceptions.InvalidColumnReferenceError: for SELECT DISTINCT, ORDER BY expressions must appear in select list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/admin/projects/python/workspace/.venv/lib/python3.8/site-packages/tortoise/__init__.py", line 636, in run_async
    loop.run_until_complete(coro)
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/admin/projects/python/workspace/db/main2.py", line 82, in run
    await Event.filter(Q(id__in=[event_first.id, event_second.id]) | Q(name="3"))
  File "/home/admin/projects/python/workspace/.venv/lib/python3.8/site-packages/tortoise/queryset.py", line 712, in _execute
    instance_list = await self._db.executor_class(
  File "/home/admin/projects/python/workspace/.venv/lib/python3.8/site-packages/tortoise/backends/base/executor.py", line 108, in execute_select
    _, raw_results = await self.db.execute_query(query.get_sql())
  File "/home/admin/projects/python/workspace/.venv/lib/python3.8/site-packages/tortoise/backends/asyncpg/client.py", line 38, in translate_exceptions_
    raise OperationalError(exc)
tortoise.exceptions.OperationalError: for SELECT DISTINCT, ORDER BY expressions must appear in select list
````

**Comment by henadzit** [comment] 2024-11-11 00:12
Looks like this was fixed a while ago. The query 

```
    query = (
        Event.filter(Q(event_id__in=[event_first.event_id, event_second.event_id]) | Q(name="3"))
        .filter(participants__not=team_second.id)
        .order_by("tournament__id")
        .distinct()
    )
    print(query.sql())
```

generates the following SQL

```
SELECT DISTINCT "event"."name","event"."modified","event"."event_id","event"."tournament_id","event"."alias" FROM "event" LEFT OUTER JOIN "tournament" "event__tournament" ON "event__tournament"."id"="event"."tournament_id" LEFT OUTER JOIN "event_team" ON "event"."event_id"="event_team"."idEvent" WHERE ("event"."event_id" IN (1,2) OR "event"."name"='3') AND ("event_team"."team_id"<>2 OR "event_team"."team_id" IS NULL) ORDER BY "event__tournament"."id" ASC
```

The code snippet to reproduce:

```
from tortoise import Tortoise, fields, run_async
from tortoise.expressions import Q
from tortoise.models import Model


class Tournament(Model):
    id = fields.SmallIntField(primary_key=True)
    name = fields.CharField(max_length=255)
    desc = fields.TextField(null=True)
    created = fields.DatetimeField(auto_now_add=True, db_index=True)

    events: fields.ReverseRelation["Event"]

    class PydanticMeta:
        exclude = ("minrelations", "uniquetogetherfieldswithfks")

    def __str__(self):
        return self.name


class Event(Model):
    event_id = fields.BigIntField(primary_key=True)
    name = fields.TextField()
    tournament: fields.ForeignKeyRelation["Tournament"] = fields.ForeignKeyField(
        "models.Tournament", related_name="events"
    )
    participants: fields.ManyToManyRelation["Team"] = fields.ManyToManyField(
        "models.Team",
        related_name="events",
        through="event_team",
        backward_key="idEvent",
    )
    modified = fields.DatetimeField(auto_now=True)
    alias = fields.IntField(null=True)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name


class Team(Model):
    id = fields.IntField(primary_key=True)
    name = fields.TextField()

    events: fields.ManyToManyRelation[Event]
    alias = fields.IntField(null=True)

    class Meta:
        ordering = ["id"]

    class PydanticMeta:
        exclude = ("minrelations",)

    def __str__(self):
        return self.name


async def main():
    await Tortoise.init(  # type: ignore
        db_url="sqlite://:memory:",
        modules={"models": ["__main__"]},
    )
    await Tortoise.generate_schemas()

    tournament_first = await Tournament.create(id=1, name="Tournament 1")
    tournament_second = await Tournament.create(id=2, name="Tournament 2")

    event_first = await Event.create(event_id=1, name="1", tournament=tournament_first)
    event_second = await Event.create(event_id=2, name="2", tournament=tournament_first)

    team_first = await Team.create(id=1, name="Team 1")
    team_second = await Team.create(id=2, name="Team 2")

    await event_first.participants.add(team_first)
    await event_second.participants.add(team_first)

    query = (
        Event.filter(Q(event_id__in=[event_first.event_id, event_second.event_id]) | Q(name="3"))
        .filter(participants__not=team_second.id)
        .order_by("tournament__id")
        .distinct()
    )

    print(query.sql())
    print(await query)


run_async(main())
```

**Comment by henadzit** [comment] 2024-11-14 21:36
Closing since we cannot reproduce it anymore.

**Closed by henadzit** 2024-11-14 21:36 UTC
