### ISSUE TITLE
DB credentials leaks in log

### ISSUE THREAD

**Issue by AlwxSin** [tortoise/tortoise-orm#481] opened 2020-08-13 10:36 UTC
**Describe the bug**
https://github.com/tortoise/tortoise-orm/blob/develop/tortoise/__init__.py#L549

After startup Tortoise writes all info about db connection into log. With all credentials like host, port, db name, username and password.

**Expected behavior**
Tortoise shouldn't write passwords anywhere.

**Comment by abondar** [comment] 2020-08-13 10:39
Duplicate of 

https://github.com/tortoise/tortoise-orm/issues/449

**Closed by abondar** 2020-08-13 10:39 UTC
